package com.sv.orderapp.order_approval.model;
// Generated May 30, 2016 4:52:23 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MRoute generated by hbm2java
 */
@Entity(name = "com.sv.orderapp.order_approval.model.MRoute")
@Table(name="m_route"
)
public class MRoute  implements java.io.Serializable {


     private Integer indexNo;
     private int version;
     private String name;
     private Set<MTransactor> MTransactors = new HashSet<MTransactor>(0);

    public MRoute() {
    }

	
    public MRoute(String name) {
        this.name = name;
    }
    public MRoute(String name, Set<MTransactor> MTransactors) {
       this.name = name;
       this.MTransactors = MTransactors;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="index_no", unique=true, nullable=false)
    public Integer getIndexNo() {
        return this.indexNo;
    }
    
    public void setIndexNo(Integer indexNo) {
        this.indexNo = indexNo;
    }

    @Column(name="version", nullable=false)
    public int getVersion() {
        return this.version;
    }
    
    public void setVersion(int version) {
        this.version = version;
    }

    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="MRoute")
    public Set<MTransactor> getMTransactors() {
        return this.MTransactors;
    }
    
    public void setMTransactors(Set<MTransactor> MTransactors) {
        this.MTransactors = MTransactors;
    }




}


