package com.sv.orderapp.order_approval.model;
// Generated May 30, 2016 4:52:23 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TOrderDetail generated by hbm2java
 */
@Entity(name = "com.sv.orderapp.order_approval.model.TOrderDetail")
@Table(name="t_order_detail"
)
public class TOrderDetail  implements java.io.Serializable {


     private Integer indexNo;
     private int version;
     private MItem MItem;
     private TOrderSummary TOrderSummary;
     private double costPrice;
     private double retailPrice;
     private double maxDiscountPercent;
     private double quantity;
     private double discountPercent;
     private double itemValue;
     private double discountValue;
     private double netValue;

    public TOrderDetail() {
    }

    public TOrderDetail(MItem MItem, TOrderSummary TOrderSummary, double costPrice, double retailPrice, double maxDiscountPercent, double quantity, double discountPercent, double itemValue, double discountValue, double netValue) {
       this.MItem = MItem;
       this.TOrderSummary = TOrderSummary;
       this.costPrice = costPrice;
       this.retailPrice = retailPrice;
       this.maxDiscountPercent = maxDiscountPercent;
       this.quantity = quantity;
       this.discountPercent = discountPercent;
       this.itemValue = itemValue;
       this.discountValue = discountValue;
       this.netValue = netValue;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="index_no", unique=true, nullable=false)
    public Integer getIndexNo() {
        return this.indexNo;
    }
    
    public void setIndexNo(Integer indexNo) {
        this.indexNo = indexNo;
    }

    @Column(name="version", nullable=false)
    public int getVersion() {
        return this.version;
    }
    
    public void setVersion(int version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="item", nullable=false)
    public MItem getMItem() {
        return this.MItem;
    }
    
    public void setMItem(MItem MItem) {
        this.MItem = MItem;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="order_summary", nullable=false)
    public TOrderSummary getTOrderSummary() {
        return this.TOrderSummary;
    }
    
    public void setTOrderSummary(TOrderSummary TOrderSummary) {
        this.TOrderSummary = TOrderSummary;
    }

    
    @Column(name="cost_price", nullable=false, precision=22, scale=0)
    public double getCostPrice() {
        return this.costPrice;
    }
    
    public void setCostPrice(double costPrice) {
        this.costPrice = costPrice;
    }

    
    @Column(name="retail_price", nullable=false, precision=22, scale=0)
    public double getRetailPrice() {
        return this.retailPrice;
    }
    
    public void setRetailPrice(double retailPrice) {
        this.retailPrice = retailPrice;
    }

    
    @Column(name="max_discount_percent", nullable=false, precision=22, scale=0)
    public double getMaxDiscountPercent() {
        return this.maxDiscountPercent;
    }
    
    public void setMaxDiscountPercent(double maxDiscountPercent) {
        this.maxDiscountPercent = maxDiscountPercent;
    }

    
    @Column(name="quantity", nullable=false, precision=22, scale=0)
    public double getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(double quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="discount_percent", nullable=false, precision=22, scale=0)
    public double getDiscountPercent() {
        return this.discountPercent;
    }
    
    public void setDiscountPercent(double discountPercent) {
        this.discountPercent = discountPercent;
    }

    
    @Column(name="item_value", nullable=false, precision=22, scale=0)
    public double getItemValue() {
        return this.itemValue;
    }
    
    public void setItemValue(double itemValue) {
        this.itemValue = itemValue;
    }

    
    @Column(name="discount_value", nullable=false, precision=22, scale=0)
    public double getDiscountValue() {
        return this.discountValue;
    }
    
    public void setDiscountValue(double discountValue) {
        this.discountValue = discountValue;
    }

    
    @Column(name="net_value", nullable=false, precision=22, scale=0)
    public double getNetValue() {
        return this.netValue;
    }
    
    public void setNetValue(double netValue) {
        this.netValue = netValue;
    }




}


