package com.sv.orderapp.rest.model;
// Generated May 30, 2016 4:14:04 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MSubCategory generated by hbm2java
 */
@Entity(name = "com.sv.orderapp.rest.model.MSubCategory")
@Table(name="m_sub_category"
)
public class MSubCategory  implements java.io.Serializable {


     private Integer indexNo;
     private int version;
     private MMainCategory MMainCategory;
     private String name;
     private Set<MItem> MItems = new HashSet<MItem>(0);

    public MSubCategory() {
    }

	
    public MSubCategory(MMainCategory MMainCategory, String name) {
        this.MMainCategory = MMainCategory;
        this.name = name;
    }
    public MSubCategory(MMainCategory MMainCategory, String name, Set<MItem> MItems) {
       this.MMainCategory = MMainCategory;
       this.name = name;
       this.MItems = MItems;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="index_no", unique=true, nullable=false)
    public Integer getIndexNo() {
        return this.indexNo;
    }
    
    public void setIndexNo(Integer indexNo) {
        this.indexNo = indexNo;
    }

    @Column(name="version", nullable=false)
    public int getVersion() {
        return this.version;
    }
    
    public void setVersion(int version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="main_category", nullable=false)
    public MMainCategory getMMainCategory() {
        return this.MMainCategory;
    }
    
    public void setMMainCategory(MMainCategory MMainCategory) {
        this.MMainCategory = MMainCategory;
    }

    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="MSubCategory")
    public Set<MItem> getMItems() {
        return this.MItems;
    }
    
    public void setMItems(Set<MItem> MItems) {
        this.MItems = MItems;
    }




}


