package com.sv.orderapp.customer_control_panel.model;
// Generated May 30, 2016 4:12:41 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MRoute generated by hbm2java
 */
@Entity(name = "com.sv.orderapp.customer_control_panel.model.MRoute")
@Table(name = "m_route")
public class MRoute implements java.io.Serializable {

    private Integer indexNo;
    private Set<MTransactor> MTransactors = new HashSet<MTransactor>(0);
    private String name;
    private int version;

    public MRoute() {
    }

    public MRoute(String name) {
        this.name = name;
    }

    public MRoute(Set<MTransactor> MTransactors, String name) {
        this.MTransactors = MTransactors;
        this.name = name;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "index_no", unique = true, nullable = false)
    public Integer getIndexNo() {
        return this.indexNo;
    }

    public void setIndexNo(Integer indexNo) {
        this.indexNo = indexNo;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "MRoute")
    public Set<MTransactor> getMTransactors() {
        return this.MTransactors;
    }

    public void setMTransactors(Set<MTransactor> MTransactors) {
        this.MTransactors = MTransactors;
    }

    @Column(name = "name", nullable = false, length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "version", nullable = false)
    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

}
