package com.sv.orderapp.user_control_panel.model;
// Generated May 30, 2016 4:52:23 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MUser generated by hbm2java
 */
@Entity(name = "com.sv.orderapp.user_control_panel.model.MUser")
@Table(name = "m_user")
public class MUser implements java.io.Serializable {

    private Integer indexNo;
    private boolean active;
    private boolean customerApproval;
    private boolean customerControlPanel;
    private boolean itemControlPanel;
    private boolean mobileApp;
    private String name;
    private boolean orderApproval;
    private String password;
    private boolean reports;
    private boolean supplierControlPanel;
    private boolean userControlPanel;
    private String username;
    private int version;

    public MUser() {
    }

    public MUser(boolean active, boolean customerApproval, boolean customerControlPanel, boolean itemControlPanel, boolean mobileApp, String name, boolean orderApproval, String password, boolean reports, boolean supplierControlPanel, boolean userControlPanel, String username) {
        this.active = active;
        this.customerApproval = customerApproval;
        this.customerControlPanel = customerControlPanel;
        this.itemControlPanel = itemControlPanel;
        this.mobileApp = mobileApp;
        this.name = name;
        this.orderApproval = orderApproval;
        this.password = password;
        this.reports = reports;
        this.supplierControlPanel = supplierControlPanel;
        this.userControlPanel = userControlPanel;
        this.username = username;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "index_no", unique = true, nullable = false)
    public Integer getIndexNo() {
        return this.indexNo;
    }

    public void setIndexNo(Integer indexNo) {
        this.indexNo = indexNo;
    }

    @Column(name = "active", nullable = false)
    public boolean isActive() {
        return this.active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    @Column(name = "customer_approval", nullable = false)
    public boolean isCustomerApproval() {
        return this.customerApproval;
    }

    public void setCustomerApproval(boolean customerApproval) {
        this.customerApproval = customerApproval;
    }

    @Column(name = "customer_control_panel", nullable = false)
    public boolean isCustomerControlPanel() {
        return this.customerControlPanel;
    }

    public void setCustomerControlPanel(boolean customerControlPanel) {
        this.customerControlPanel = customerControlPanel;
    }

    @Column(name = "item_control_panel", nullable = false)
    public boolean isItemControlPanel() {
        return this.itemControlPanel;
    }

    public void setItemControlPanel(boolean itemControlPanel) {
        this.itemControlPanel = itemControlPanel;
    }

    @Column(name = "mobileApp", nullable = false)
    public boolean isMobileApp() {
        return this.mobileApp;
    }

    public void setMobileApp(boolean mobileApp) {
        this.mobileApp = mobileApp;
    }

    @Column(name = "name", nullable = false, length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "order_approval", nullable = false)
    public boolean isOrderApproval() {
        return this.orderApproval;
    }

    public void setOrderApproval(boolean orderApproval) {
        this.orderApproval = orderApproval;
    }

    @Column(name = "password", nullable = false, length = 25)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name = "reports", nullable = false)
    public boolean isReports() {
        return this.reports;
    }

    public void setReports(boolean reports) {
        this.reports = reports;
    }

    @Column(name = "supplier_control_panel", nullable = false)
    public boolean isSupplierControlPanel() {
        return this.supplierControlPanel;
    }

    public void setSupplierControlPanel(boolean supplierControlPanel) {
        this.supplierControlPanel = supplierControlPanel;
    }

    @Column(name = "user_control_panel", nullable = false)
    public boolean isUserControlPanel() {
        return this.userControlPanel;
    }

    public void setUserControlPanel(boolean userControlPanel) {
        this.userControlPanel = userControlPanel;
    }

    @Column(name = "username", nullable = false, length = 25)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Column(name = "version", nullable = false)
    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

}
