package com.sv.orderapp.item_manager.model;
// Generated May 30, 2016 4:12:41 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MItem generated by hbm2java
 */
@Entity(name = "com.sv.orderapp.item_manager.model.MItem")
@Table(name = "m_item")
public class MItem implements java.io.Serializable {

    private Integer indexNo;
    private int version;
    private MDepartment MDepartment;
    private MMainCategory MMainCategory;
    private MSubCategory MSubCategory;
    private MTransactor MTransactor;
    private String code;
    private String name;
    private String printDescription;
    private String defaultUnit;
    private double costPrice;
    private double retailPrice;
    private double maxDiscountPercent;
    private boolean active;

    public MItem() {
    }

    public MItem(MTransactor MTransactor, String code, String name, String printDescription, String defaultUnit, double costPrice, double retailPrice, double maxDiscountPercent, boolean active) {
        this.MTransactor = MTransactor;
        this.code = code;
        this.name = name;
        this.printDescription = printDescription;
        this.defaultUnit = defaultUnit;
        this.costPrice = costPrice;
        this.retailPrice = retailPrice;
        this.maxDiscountPercent = maxDiscountPercent;
        this.active = active;
    }

    public MItem(MDepartment MDepartment, MMainCategory MMainCategory, MSubCategory MSubCategory, MTransactor MTransactor, String code, String name, String printDescription, String defaultUnit, double costPrice, double retailPrice, double maxDiscountPercent, boolean active) {
        this.MDepartment = MDepartment;
        this.MMainCategory = MMainCategory;
        this.MSubCategory = MSubCategory;
        this.MTransactor = MTransactor;
        this.code = code;
        this.name = name;
        this.printDescription = printDescription;
        this.defaultUnit = defaultUnit;
        this.costPrice = costPrice;
        this.retailPrice = retailPrice;
        this.maxDiscountPercent = maxDiscountPercent;
        this.active = active;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "index_no", unique = true, nullable = false)
    public Integer getIndexNo() {
        return this.indexNo;
    }

    public void setIndexNo(Integer indexNo) {
        this.indexNo = indexNo;
    }

    @Column(name = "version", nullable = false)
    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "department")
    public MDepartment getMDepartment() {
        return this.MDepartment;
    }

    public void setMDepartment(MDepartment MDepartment) {
        this.MDepartment = MDepartment;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "main_category")
    public MMainCategory getMMainCategory() {
        return this.MMainCategory;
    }

    public void setMMainCategory(MMainCategory MMainCategory) {
        this.MMainCategory = MMainCategory;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "sub_category")
    public MSubCategory getMSubCategory() {
        return this.MSubCategory;
    }

    public void setMSubCategory(MSubCategory MSubCategory) {
        this.MSubCategory = MSubCategory;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "supplier", nullable = false)
    public MTransactor getMTransactor() {
        return this.MTransactor;
    }

    public void setMTransactor(MTransactor MTransactor) {
        this.MTransactor = MTransactor;
    }

    @Column(name = "code", nullable = false, length = 10)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "name", nullable = false, length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "print_description", nullable = false, length = 50)
    public String getPrintDescription() {
        return this.printDescription;
    }

    public void setPrintDescription(String printDescription) {
        this.printDescription = printDescription;
    }

    @Column(name = "default_unit", nullable = false, length = 50)
    public String getDefaultUnit() {
        return this.defaultUnit;
    }

    public void setDefaultUnit(String defaultUnit) {
        this.defaultUnit = defaultUnit;
    }

    @Column(name = "cost_price", nullable = false, precision = 22, scale = 0)
    public double getCostPrice() {
        return this.costPrice;
    }

    public void setCostPrice(double costPrice) {
        this.costPrice = costPrice;
    }

    @Column(name = "retail_price", nullable = false, precision = 22, scale = 0)
    public double getRetailPrice() {
        return this.retailPrice;
    }

    public void setRetailPrice(double retailPrice) {
        this.retailPrice = retailPrice;
    }

    @Column(name = "max_discount_percent", nullable = false, precision = 22, scale = 0)
    public double getMaxDiscountPercent() {
        return this.maxDiscountPercent;
    }

    public void setMaxDiscountPercent(double maxDiscountPercent) {
        this.maxDiscountPercent = maxDiscountPercent;
    }

    @Column(name = "active", nullable = false)
    public boolean isActive() {
        return this.active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

}
