package com.sv.orderapp.rest.model;
// Generated May 30, 2016 4:14:04 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * MDepartment generated by hbm2java
 */
@Entity
@Table(name="m_department"
    ,catalog="estoke"
)
public class MDepartment  implements java.io.Serializable {


     private Integer indexNo;
     private int version;
     private String name;
     private Set<MItem> MItems = new HashSet<MItem>(0);
     private Set<MMainCategory> MMainCategories = new HashSet<MMainCategory>(0);

    public MDepartment() {
    }

	
    public MDepartment(String name) {
        this.name = name;
    }
    public MDepartment(String name, Set<MItem> MItems, Set<MMainCategory> MMainCategories) {
       this.name = name;
       this.MItems = MItems;
       this.MMainCategories = MMainCategories;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="index_no", unique=true, nullable=false)
    public Integer getIndexNo() {
        return this.indexNo;
    }
    
    public void setIndexNo(Integer indexNo) {
        this.indexNo = indexNo;
    }

    @Version
    @Column(name="version", nullable=false)
    public int getVersion() {
        return this.version;
    }
    
    public void setVersion(int version) {
        this.version = version;
    }

    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="MDepartment")
    public Set<MItem> getMItems() {
        return this.MItems;
    }
    
    public void setMItems(Set<MItem> MItems) {
        this.MItems = MItems;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="MDepartment")
    public Set<MMainCategory> getMMainCategories() {
        return this.MMainCategories;
    }
    
    public void setMMainCategories(Set<MMainCategory> MMainCategories) {
        this.MMainCategories = MMainCategories;
    }




}


