package com.sv.orderapp.rest.model;
// Generated May 30, 2016 4:14:04 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MUserRole generated by hbm2java
 */
@Entity
@Table(name="m_user_role"
    ,catalog="estoke"
)
public class MUserRole  implements java.io.Serializable {


     private String code;
     private String name;
     private Set<RUserRoleTransactionType> RUserRoleTransactionTypes = new HashSet<RUserRoleTransactionType>(0);

    public MUserRole() {
    }

	
    public MUserRole(String code, String name) {
        this.code = code;
        this.name = name;
    }
    public MUserRole(String code, String name, Set<RUserRoleTransactionType> RUserRoleTransactionTypes) {
       this.code = code;
       this.name = name;
       this.RUserRoleTransactionTypes = RUserRoleTransactionTypes;
    }
   
     @Id 

    
    @Column(name="code", unique=true, nullable=false, length=10)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="name", nullable=false, length=25)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="MUserRole")
    public Set<RUserRoleTransactionType> getRUserRoleTransactionTypes() {
        return this.RUserRoleTransactionTypes;
    }
    
    public void setRUserRoleTransactionTypes(Set<RUserRoleTransactionType> RUserRoleTransactionTypes) {
        this.RUserRoleTransactionTypes = RUserRoleTransactionTypes;
    }




}


