package com.sv.orderapp.supplier_control_panel.model;
// Generated May 20, 2016 10:56:32 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MRoute generated by hbm2java
 */
@Entity(name = "com.sv.orderapp.supplier_control_panel.model.MRoute")
@Table(name = "m_route")
public class MRoute implements java.io.Serializable {

    private Integer indexNo;
    private String name;

    public MRoute() {
    }

    public MRoute(String name) {
        this.name = name;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "index_no", unique = true, nullable = false)
    public Integer getIndexNo() {
        return this.indexNo;
    }

    public void setIndexNo(Integer indexNo) {
        this.indexNo = indexNo;
    }

    @Column(name = "name", nullable = false, length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
