package com.sv.orderapp.item_manager.model;
// Generated May 20, 2016 10:56:32 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MMainCategory generated by hbm2java
 */
@Entity(name = "com.sv.orderapp.item_manager.model.MMainCategory")
@Table(name = "m_main_category")
public class MMainCategory implements java.io.Serializable {

    private Integer indexNo;
    private Integer department;
    private String name;

    public MMainCategory() {
    }

    public MMainCategory(Integer department, String name) {
        this.department = department;
        this.name = name;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "index_no", unique = true, nullable = false)
    public Integer getIndexNo() {
        return this.indexNo;
    }

    public void setIndexNo(Integer indexNo) {
        this.indexNo = indexNo;
    }

    @Column(name = "department", nullable = false)
    public Integer getDepartment() {
        return this.department;
    }

    public void setDepartment(Integer department) {
        this.department = department;
    }

    @Column(name = "name", nullable = false, length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
