package com.sv.orderapp.item_manager.model;
// Generated May 20, 2016 10:56:32 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MSubCategory generated by hbm2java
 */
@Entity(name = "com.sv.orderapp.item_manager.model.MSubCategory")
@Table(name = "m_sub_category")
public class MSubCategory implements java.io.Serializable {

    private Integer indexNo;
    private Integer mainCategory;
    private String name;

    public MSubCategory() {
    }

    public MSubCategory(Integer mainCategory, String name) {
        this.mainCategory = mainCategory;
        this.name = name;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "index_no", unique = true, nullable = false)
    public Integer getIndexNo() {
        return this.indexNo;
    }

    public void setIndexNo(Integer indexNo) {
        this.indexNo = indexNo;
    }

    @Column(name = "main_category", nullable = false)
    public Integer getMainCategory() {
        return this.mainCategory;
    }

    public void setMainCategory(Integer mainCategory) {
        this.mainCategory = mainCategory;
    }

    @Column(name = "name", nullable = false, length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
