package com.sv.orderapp.item_manager.model;
// Generated May 20, 2016 10:56:32 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MTransactor generated by hbm2java
 */
@Entity(name = "com.sv.orderapp.item_manager.model.MTransactor")
@Table(name = "m_transactor")
public class MTransactor implements java.io.Serializable {

    private Integer indexNo;
    private boolean active;
    private String code;
    private String name;
    private boolean supplier;

    public MTransactor() {
    }

    public MTransactor(boolean active, String code, String name, boolean supplier) {
        this.active = active;
        this.code = code;
        this.name = name;
        this.supplier = supplier;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "index_no", unique = true, nullable = false)
    public Integer getIndexNo() {
        return this.indexNo;
    }

    public void setIndexNo(Integer indexNo) {
        this.indexNo = indexNo;
    }

    @Column(name = "active", nullable = false)
    public boolean isActive() {
        return this.active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    @Column(name = "code", nullable = false, length = 10)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "name", nullable = false, length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "supplier", nullable = false)
    public boolean isSupplier() {
        return this.supplier;
    }

    public void setSupplier(boolean supplier) {
        this.supplier = supplier;
    }

}
