package com.sv.orderapp.customer_control_panel.model;
// Generated May 20, 2016 9:13:35 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MTransactor generated by hbm2java
 */
@Entity(name = "com.sv.orderapp.customer_control_panel.model.MTransactor")
@Table(name = "m_transactor")
public class MTransactor implements java.io.Serializable {

    private int indexNo;
    private MRoute MRoute;
    private String code;
    private String name;
    private String contactPerson;
    private String mobile;
    private String addressLine1;
    private String addressLine2;
    private String addressLine3;
    private String telephone1;
    private String telephone2;
    private String fax;
    private String email;
    private double creditLimit;
    private double creditAmount;
    private boolean client;
    private boolean supplier;
    private boolean approved;
    private boolean active;

    public MTransactor() {
    }

    public MTransactor(int indexNo, String code, String name, double creditLimit, double creditAmount, boolean client, boolean supplier, boolean approved, boolean active) {
        this.indexNo = indexNo;
        this.code = code;
        this.name = name;
        this.creditLimit = creditLimit;
        this.creditAmount = creditAmount;
        this.client = client;
        this.supplier = supplier;
        this.approved = approved;
        this.active = active;
    }

    public MTransactor(int indexNo, MRoute MRoute, String code, String name, String contactPerson, String mobile, String addressLine1, String addressLine2, String addressLine3, String telephone1, String telephone2, String fax, String email, double creditLimit, double creditAmount, boolean client, boolean supplier, boolean approved, boolean active) {
        this.indexNo = indexNo;
        this.MRoute = MRoute;
        this.code = code;
        this.name = name;
        this.contactPerson = contactPerson;
        this.mobile = mobile;
        this.addressLine1 = addressLine1;
        this.addressLine2 = addressLine2;
        this.addressLine3 = addressLine3;
        this.telephone1 = telephone1;
        this.telephone2 = telephone2;
        this.fax = fax;
        this.email = email;
        this.creditLimit = creditLimit;
        this.creditAmount = creditAmount;
        this.client = client;
        this.supplier = supplier;
        this.approved = approved;
        this.active = active;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "index_no", unique = true, nullable = false)
    public int getIndexNo() {
        return this.indexNo;
    }

    public void setIndexNo(int indexNo) {
        this.indexNo = indexNo;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "route")
    public MRoute getMRoute() {
        return this.MRoute;
    }

    public void setMRoute(MRoute MRoute) {
        this.MRoute = MRoute;
    }

    @Column(name = "code", nullable = false, length = 10)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "name", nullable = false, length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "contact_person", length = 50)
    public String getContactPerson() {
        return this.contactPerson;
    }

    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson;
    }

    @Column(name = "mobile", length = 25)
    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    @Column(name = "address_line1", length = 50)
    public String getAddressLine1() {
        return this.addressLine1;
    }

    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }

    @Column(name = "address_line2", length = 50)
    public String getAddressLine2() {
        return this.addressLine2;
    }

    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }

    @Column(name = "address_line3", length = 45)
    public String getAddressLine3() {
        return this.addressLine3;
    }

    public void setAddressLine3(String addressLine3) {
        this.addressLine3 = addressLine3;
    }

    @Column(name = "telephone1", length = 25)
    public String getTelephone1() {
        return this.telephone1;
    }

    public void setTelephone1(String telephone1) {
        this.telephone1 = telephone1;
    }

    @Column(name = "telephone2", length = 25)
    public String getTelephone2() {
        return this.telephone2;
    }

    public void setTelephone2(String telephone2) {
        this.telephone2 = telephone2;
    }

    @Column(name = "fax", length = 25)
    public String getFax() {
        return this.fax;
    }

    public void setFax(String fax) {
        this.fax = fax;
    }

    @Column(name = "email", length = 50)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "credit_limit", nullable = false, precision = 22, scale = 0)
    public double getCreditLimit() {
        return this.creditLimit;
    }

    public void setCreditLimit(double creditLimit) {
        this.creditLimit = creditLimit;
    }

    @Column(name = "credit_amount", nullable = false, precision = 22, scale = 0)
    public double getCreditAmount() {
        return this.creditAmount;
    }

    public void setCreditAmount(double creditAmount) {
        this.creditAmount = creditAmount;
    }

    @Column(name = "client", nullable = false)
    public boolean isClient() {
        return this.client;
    }

    public void setClient(boolean client) {
        this.client = client;
    }

    @Column(name = "supplier", nullable = false)
    public boolean isSupplier() {
        return this.supplier;
    }

    public void setSupplier(boolean supplier) {
        this.supplier = supplier;
    }

    @Column(name = "approved", nullable = false)
    public boolean isApproved() {
        return this.approved;
    }

    public void setApproved(boolean approved) {
        this.approved = approved;
    }

    @Column(name = "active", nullable = false)
    public boolean isActive() {
        return this.active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

}
